"""empty message

Revision ID: 34819732a0d2
Revises: dc65d371f7d4
Create Date: 2023-05-13 19:59:53.992608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34819732a0d2'
down_revision = 'dc65d371f7d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('chromebook',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.String(length=80), nullable=False),
    sa.Column('serial_number', sa.String(length=80), nullable=False),
    sa.Column('is_loaned', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('loaned_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identifier'),
    sa.UniqueConstraint('serial_number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chromebook')
    op.drop_table('user')
    # ### end Alembic commands ###
