"""Added email_sent column

Revision ID: 55c529ed7e55
Revises: 6291f2315cf8
Create Date: 2023-09-22 22:35:22.461138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55c529ed7e55'
down_revision = '6291f2315cf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chromebook', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_sent', sa.Boolean(), nullable=False, server_default='false'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chromebook', schema=None) as batch_op:
        batch_op.drop_column('email_sent')

    # ### end Alembic commands ###
