"""Add ChromebookHistory table

Revision ID: 76b74ca2d183
Revises: 8c74aa9650a1
Create Date: 2023-09-22 18:38:35.133662

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '76b74ca2d183'
down_revision = '8c74aa9650a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chromebook_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chromebook_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('action_date', sa.DateTime(), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['chromebook_id'], ['chromebook.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chromebook', schema=None) as batch_op:
        batch_op.drop_column('history')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chromebook', schema=None) as batch_op:
        batch_op.add_column(sa.Column('history', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))

    op.drop_table('chromebook_history')
    # ### end Alembic commands ###
