"""remove is_loaned from chromebook

Revision ID: 8ad8f41c8ef0
Revises: a1cb4478abe8
Create Date: 2023-09-18 18:52:57.277659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ad8f41c8ef0'
down_revision = 'a1cb4478abe8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chromebook', schema=None) as batch_op:
        batch_op.drop_column('is_loaned')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chromebook', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_loaned', sa.BOOLEAN(), nullable=False))

    # ### end Alembic commands ###
