"""Added history to Chromebook

Revision ID: 8c74aa9650a1
Revises: 8ad8f41c8ef0
Create Date: 2023-09-18 20:18:56.395830

"""
from sqlalchemy import Text
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8c74aa9650a1'
down_revision = '8ad8f41c8ef0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chromebook', schema=None) as batch_op:
        batch_op.add_column(sa.Column('history', postgresql.JSON(astext_type=Text()), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chromebook', schema=None) as batch_op:
        batch_op.drop_column('history')

    # ### end Alembic commands ###
