"""Added status column to Chromebook

Revision ID: a1cb4478abe8
Revises: 70ef0db4ac72
Create Date: 2023-09-18 18:42:01.395785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1cb4478abe8'
down_revision = '70ef0db4ac72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chromebook', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=80), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chromebook', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
