"""Added serial_number to Chromebook

Revision ID: dc65d371f7d4
Revises: 
Create Date: 2023-05-13 19:14:02.997106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc65d371f7d4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chromebook', schema=None) as batch_op:
        batch_op.add_column(sa.Column('serial_number', sa.String(length=80), nullable=False))
        batch_op.create_unique_constraint(None, ['serial_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chromebook', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('serial_number')

    # ### end Alembic commands ###
